name: Update Readme

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download awesome-list-generator and generate list
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
          GENERATOR_VERSION: "1.3.0"
        run: |
          sudo apt install wget -y
          wget https://github.com/iLLeniumStudios/awesome-list-generator/releases/download/v${GENERATOR_VERSION}/awesome-list-generator_${GENERATOR_VERSION}_Linux_x86_64.tar.gz
          tar -xvf awesome-list-generator_${GENERATOR_VERSION}_Linux_x86_64.tar.gz
          ./awesome-list-generator --config config.yaml --output README.md
          rm -rf awesome-list-generator*
      - name: Push generated list
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push 
